# Generated by Django 6.1.1 on 2026-09-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='title',
            new_name='title_ar',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='title_en',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
